name: Second
on: 
  push:
    branches:
      - workflows2

jobs:

  job1:
    name: 'Trabajo 1'
    runs-on: ubuntu-20.04
    steps: 
      - name: 'Checkout repo'
        uses: actions/checkout@v3

      - name: Ejecuto script de Python
        run: python eati.py Workflow Dependencies

  job2:
    name: 'Trabajo 2'
    runs-on: windows-2019
    steps:
      - run: Get-Command
  
  job3:
    name: 'Trabajo 3'
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - run: env

  job4:
    name: 'Trabajo 4'
    runs-on: ubuntu-latest
    steps:
      - run: cat /etc/*release

  job5:
    name: 'Trabajo 5'
    runs-on: macos-latest
    needs: [job3, job4]
    steps:
      - run: echo "Fin workflow"
    



