name: Third
on: 
  push:
    branches:
      - thirdday

jobs:

  job1:
    name: 'Ver archivos de jmoyano/eati2023'
    runs-on: ubuntu-latest
    steps: 
      - name: 'Checkout repo de jmoyano/eati2023@main'
        uses: actions/checkout@v3
        with:
          repository: jmoyano/eati2023
          ref: main
          path: ./main
        
      - name: Ejecuto cat en branch main
        run: cat main/message.txt

      - name: 'Checkout repo de jmoyano/eati2023@anotherbranch'
        uses: actions/checkout@v3
        with:
          repository: jmoyano/eati2023
          ref: anotherbranch
          path: ./anotherbranch

      - name: Ejecuto cat en branch "anotherbranch"
        run: cat anotherbranch/message.txt








