name: Third4
on: 
  push:
    branches:
      - thirdday

env:  
  PATH: repo_profe
  FILE: main

jobs:
  build:    
    name: 'Build Job'
    runs-on: ubuntu-latest
    steps: 
      # Descargo el repo del profe
      - name: 'Checkout de jmoyano/utious-meme@main'
        uses: actions/checkout@v3
        with:
          repository: jmoyano/cautious-meme
          ref: main
          path: ./${{ env.PATH  }}

      # Compilo y genero ejecutable
      - name: 'Compilar main.c'
        run: gcc ${PATH}/main.c -o ${PATH}/${FILE}

      # Subo el ejecutable
      - name: 'Usando upload-artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'Mi-artefacto'
          path: ${{ env.PATH }}/${{ env.FILE }}

  test:
    name: 'Test Job'
    runs-on: ubuntu-latest
    needs: [build]
    steps:   
      - uses: actions/download-artifact@v3
        with:
          name: Mi-artefacto
          path: ${{ env.PATH }}
      - run: ls
      - run: ls main
      - run: ./${{ env.PATH }}/${{ env.FILE }}
      - run: tree


