name: Third4
on: 
  push:
    branches:
      - thirdday

env:  
  PATH_FILE: repo_descargado
  FILE: ejecutable
  FULL_FILE_PATH: ${{PATH_FILE}}/${{FILE}}

jobs:
  build:    
    name: 'Build Job'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${FULL_FILE_PATH}
      # Descargo el repo del profe
      - name: 'Checkout de jmoyano/cautious-meme@main'
        uses: actions/checkout@v3
        with:
          repository: jmoyano/cautious-meme
          ref: main
          path: ./${{ env.PATH_FILE }}

      # Compilo y genero ejecutable
      - name: 'Compilar main.c'
        run: gcc ${FULL_FILE_PATH}.c -o ${FULL_FILE_PATH}

      # Subo el ejecutable
      - name: 'Usando upload-artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'Mi-artefacto'
          path: ${{ env.FULL_FILE_PATH }}

  test:
    name: 'Test Job'
    runs-on: ubuntu-latest
    needs: [build]
    steps:   
      - uses: actions/download-artifact@v3
        with:
          name: Mi-artefacto
          path: ${{ env.PATH_FILE }}
      - run: ls
      - run: ls ${PATH_FILE}
      - run: ./${{ env.FULL_FILE_PATH }}
      - run: tree


