name: Third4
on: 
  push:
    branches:
      - thirdday

env:  
  PATH_FILE: repo_descargado
  FILE: main

jobs:
  build:    
    name: 'Build Job'
    runs-on: ubuntu-latest
    steps:
      # Descargo el repo del profe
      - name: 'Checkout de jmoyano/cautious-meme@main'
        uses: actions/checkout@v3
        with:
          repository: jmoyano/cautious-meme
          ref: main
          path: ./${{ env.PATH_FILE }}

      # Compilo y genero ejecutable
      - name: 'Compilar main.c'
        run: gcc ${PATH_FILE}/main.c -o ${PATH_FILE}/${FILE}

      # Subo el ejecutable
      - name: 'Usando upload-artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'Mi-artefacto'
          path: ${{ env.PATH_FILE }}/${{ env.FILE }}

  test:
    name: 'Test Job'
    runs-on: ubuntu-latest
    needs: [build]
    steps:   
      - uses: actions/download-artifact@v3
        with:
          name: Mi-artefacto
          path: .
      - run: ls
      - run: ls ${PATH_FILE}
      - run: ./${{ env.FILE }}
      - run: tree


